openapi: '3.0.2'
info:
  description: "Central Loom REST API"
  version: "1.0.0"
  title: "MetaLoom Loom API"
servers:
  - url: https://demo.metaloom.io/v1

paths:
  # User
  /users:
    summary: "Endpoint to access users."
    get:
      responses:
        '200':
          description: "Users loaded"
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UserListResponse'
              examples:
                UserListResponse:
                  $ref: '#/components/schemas/UserListResponse/example'

components:
  schemas:
    # User / Response
    UserResponse:
      properties:
        uuid:
          type: string
          description: "UUID of the user."
      example:
        uuid: "217f8c981ada4642bf8c981adaa642c3"
        
    # User / List Response
    UserListResponse:
      type: array
      items:
        $ref: "#/components/schemas/UserResponse"
      example:
        - uuid: "4fbe29c9-c69a-4572-85e4-19bc433c6cf7"
        - uuid: "054e4e69-21b2-4662-aacd-2c7ee2d3dff2"
  